version: '3.9'

services:
  api:
    container_name: api
    command: 'npm run start:dev'
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - database
    networks:
      - pagarme-credit-card-network

  database:
    image: postgres:14.5-alpine
    hostname: database
    container_name: database
    env_file:
      - .env
    networks:
      - pagarme-credit-card-network

networks:
  pagarme-credit-card-network:
    name: pagarme-credit-card-network
