version: '3'

services:
  api:
    container_name: 'api'
    command: 'npm run dev'
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    environment:
      - DB_NAME=postgres
      - DB_HOST=${DB_HOST}
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:14.5-alpine
    container_name: 'database'
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
